export const data = [
  ["BUMP", "Bring Up My Post"],
  ["HER", "Having Everything Revealed"],
  ["NERD", "No one Ever Really Dies"],
  [
    "SHIELD",
    "Strategic Homeland Intervention, Enforcement and Logistics Division",
  ],
  ["WAL", "Waste Allocation Load Lifter Earth-Class"],
  ["YAHOO", "Yet Another Hierarchical Officious Oracle"],
  ["ASAP", "As Soon As Possible"],
  ["BAE", "Before Anyone Else"],
  ["BOLO", "Be On the LookOut"],
  ["FISH", "First In, Still Here"],
  ["FOMO", "Fear Of Missing Out"],
  ["GIF", "Graphics Interchange Format (but is it “jif” or “gif”?)"],
  ["LOL", "Laughing Out Loud (some people pronounce this as “lahl”)"],
  ["YOLO", "You Only Live Once"],
  ["AFK", "Away From Keyboard"],
  ["BBL", "Be Back Later"],
  ["BBS", "Be Back Soon"],
  ["BEG", "Big Evil Grin"],
  ["BRB", "Be Right Back"],
  ["BTW", "By The Way"],
  ["EG", "Evil Grin"],
  ["IDK", "I Don't Know"],
  ["IMO", "In My Opinion"],
  ["IRL", "In Real Life"],
  ["LMK", "Let Me Know"],
  ["NOYB", "None of Your Business"],
  ["OMG", "Oh My God"],
  ["POS", "Parents Over Shoulder"],
  ["ROFL", "Rolling On the Floor Laughing"],
  ["SMH", "Shaking My Head"],
  ["TTYL", "Talk To You Later"],
  ["WTH", "What The Heck (or Hell)"],
  ["AWOL", "Absent WithOut Leave"],
  ["FUBAR", "F***ed Up Beyond All Recognition"],
  ["OSHA", "Occupational Safety and Health Administration"],
  ["NAFTA", "North American Free Trade Agreement"],
  ["NASA", "National Aeronautics and Space Administration"],
  ["POTUS", "President of the United States"],
  ["SCOTUS", "Supreme Court of the United States"],
  ["SWAT", "Special Weapons And Tactics"],
  ["CIA", "Central Intelligence Agency"],
  ["CPS", "Child Protective Services"],
  ["CSI", "Crime Scene Investigation"],
  ["DMV", "Division of Motor Vehicles"],
  ["DNC", "Democratic National Committee"],
  ["DOD", "Department of Defense"],
  ["DON", "Department of the Navy"],
  ["DZ", "Drop Zone"],
  ["FBI", "Federal Bureau of Investigation"],
  ["GIB", "GI Bill"],
  ["MIA", "Missing In Action"],
  ["POW", "Prisoner Of War"],
  ["RNC", "Republican National Committee"],
  ["REAP", "Reserve Education Assistance Program"],
  ["UN", "United Nations"],
  ["USAF", "United States Air Force"],
  ["AIDS", "Acquired Immune Deficiency Syndrome"],
  ["DARE", "Drug Abuse Resistance Education"],
  [
    "PEMDAS",
    "Parentheses, Exponent, Multiplication, Division, Addition, Subtraction (math order of operations)",
  ],
  ["RADAR", "Radio Detection And Ranging"],
  ["SONAR", "Sound Navigation And Ranging"],
  ["ZIP code", "Zone Improvement Plan code"],
  ["ABS", "Anti-lock Braking System"],
  ["ADD", "Attention Deficit Disorder"],
  ["ADHD", "Attention Deficit Hyperactivity Disorder"],
  ["AMA", "Against Medical Advice"],
  ["CDC", "Centers for Disease Control and Prevention"],
  ["DOA", "Dead On Arrival"],
  ["DOB", "Date Of Birth"],
  ["DIY", "Do It Yourself"],
  ["ESL", "English As A Second Language"],
  ["FAQ", "Frequently Asked Questions"],
  ["HIV", "Human Immunodeficiency Virus"],
  ["IQ", "Intelligence Quotient"],
  ["MD", "Medical Doctor"],
  ["OTC", "Over The Counter"],
  ["PPV", "Pay Per View"],
  ["PS", "Post Script"],
  ["SUV", "Sports Utility Vehicle"],
  ["UFO", "Unidentified Flying Object"],
  [
    "CAPTCHA",
    "Completely Automated Public Turing Test (to tell Computers and Humans Apart)",
  ],
  ["DAEMON", "Disk And Execution Monitor"],
  ["KISS", "Keep It Simple, Stupid"],
  ["NASDAQ", "National Association of Securities Dealers Automated Quotations"],
  ["SWOT", "Strengths, Weaknesses, Opportunities, Threats"],
  [
    "SMART Goals",
    "Specific, Measurable, Attainable, Realistic, Time-bound Goals",
  ],
  ["TED", "Tell me, Explain to me, Describe to me"],
  ["ADP", "Automated Data Processing"],
  ["AKA", "Also Known As"],
  ["CDT", "Central Daylight Time"],
  ["CST", "Central Standard Time"],
  ["DBA", "Doing Business As"],
  ["DND", "Do Not Disturb"],
  ["EDS", "Electronic Data Systems"],
  ["EOD", "End of Day"],
  ["EOW", "End of Week"],
  ["EDT", "Eastern Daylight Time"],
  ["EST", "Eastern Standard Time"],
  ["ETA", "Estimated Time of Arrival"],
  ["FYI", "For Your Information"],
  ["HR", "Human Resources"],
  ["MBA", "Masters of Business Administration"],
  ["MDT", "Mountain Daylight Time"],
  ["MST", "Mountain Standard Time"],
  ["POS", "Point Of Service"],
  ["PR", "Public Relations"],
  ["PDT", "Pacific Daylight Time"],
  ["PST", "Pacific Standard Time"],
  ["TBA", "To Be Announced"],
  ["TBD", "To Be Determined"],
  ["LAG", "Foreign Language Association of Georgia"],
  ["ADD", "Mothers Against Drunk Driving"],
  ["AWS", "Progressive Animal Welfare Society"],
  ["PETA", "People for the Ethical Treatment of Animals"],
  ["A", "Alcoholics Anonymous"],
  ["ARP", "American Association of Retired Persons"],
  ["DA", "American Dental Association"],
  ["FL", "American Football League"],
  ["MA", "American Medical Association"],
  ["PA", "American Psychological Association"],
  ["SPN", "Entertainment and Sports Programming Network"],
  ["LDR", "Long Distance Relationship"],
  ["LA", "Modern Language Association"],
  ["MOTOS", "Member Of The Opposite Sex"],
  ["MOTSS", "Member Of The Same Sex"],
  ["BA", "National Basketball Association"],
  ["FL", "National Football League"],
  ["HL", "National Hockey League"],
  ["GA", "Professional Golfer’s Association"],
  ["PCA", "Society for the Prevention of Cruelty to Animals"],
  ["SO", "Significant Other"],
  ["WF", "Single White Female"],
  ["WM", "Single White Male"],
  ["WE", "World Wrestling Entertainment"],
  ["G2G", "Got to go"],
  ["MSG", "Message"],
  ["PAW", "Parents are watching"],
  ["PITR", "Parent in the room"],
  ["PBB", "Parent behind back"],
  ["POMS", "Parent over my shoulder"],
  ["KPC", "Keeping parents clueless"],
  ["PAH", "Parent at home"],
  ["HIFW", "How I feel when"],
  ["TFW", "That feeling when."],
  ["MFW", "My face when"],
  ["MRW", "My reaction when"],
  ["IFYP", "I feel your pain"],
  ["LOL", "Laughing out loud"],
  ["TNTL", "Trying not to laugh"],
  ["JK", "Just kidding"],
  ["IDC", "I don’t care"],
  ["ILY", "I love you"],
  ["IMU", "I miss you"],
  ["ADIH", "Another day in hell"],
  ["IDC", "I don’t care"],
  ["ZZZ", "Sleeping, bored, tired"],
  ["WYWH", "Wish you were here"],
  ["TIME", "Tears in my eyes"],
  ["BAE", "Before anyone else"],
  ["SSDD", "Same stuff, different day"],
  ["QQ", "Crying"],
  ["FIMH", "Forever in my heart"],
  ["BSAAW", "Big smile and a wink"],
  ["BWL", "Bursting with laughter"],
  ["CSL", "Can’t stop laughing"],
  ["IMOIMHO", "In my opinionIn my humble opinion"],
  ["OMDB", "Over my dead body"],
  ["NTH", "Nice to have. what does nth mean in texting messaging"],
  ["POV", "Point of View"],
  ["TBH", "To be honest"],
  ["FTW", "For the win"],
  ["FTL", "For the loss"],
  ["YNK", "You never know"],
  ["SMH", "Shaking my head"],
  ["SRSLY", "Seriously"],
  ["YGTR", "You got that right"],
  ["GMTA", "Great minds think alike"],
  ["AYMM", "Are you my mother?"],
  ["CWOT", "Complete waste of time"],
  ["IANAL", "I am not a lawyer"],
  ["AFAIK", "As far as I know"],
  ["AFAIR", "As far as I remember"],
  ["AFAIC", "As far as I’m concerned"],
  ["AAMOF", "As a matter of fact"],
  ["IIRC", "If I remember correctly"],
  ["DM", "Direct message"],
  ["AFAICT", "As far as I can tell"],
  ["TL;DR", "Too long; didn’t read"],
  ["IRL", "In real life"],
  ["TIL", "Today I learned"],
  ["SOML", "Story of my life."],
  ["EMBM", "Early morning business meeting"],
  ["J4F", "Just for fun"],
  ["JSYK", "Just so you know"],
  ["FAWC", "For anyone who cares"],
  ["RLRT", "Real life retweet"],
  ["OH", "Overheard"],
  ["WUZUP", "What’s up?"],
  ["CS", "Career suicide"],
  ["DWH", "During work hours"],
  ["NSFW", "Not safe for work"],
  ["NSFL", "Not safe for life"],
  ["SFW", "Safe for work"],
  ["GRAS", "Generally recognised as safe"],
  ["NBD", "Not big deal"],
  ["OC", "Original content"],
  ["4AO", "For adults only"],
  ["OP", "Original poster"],
  ["ICYMI", "In case you missed it"],
  ["JIC", "Just in case"],
  ["NAGI", "Not a good idea"],
  ["GOI", "Get over it"],
  ["RBTL", "Read between the lines"],
  ["AYOR", "At your own risk"],
  ["DIY", "Do it yourself"],
  ["E123", "Easy as one, two, three"],
  ["GAHOY", "Get a hold of yourself"],
  ["TMB", "Tweet me back"],
  ["WTPA", "Where the party at?"],
  ["DAE", "Does anyone else?"],
  ["PRT", "Please retweet"],
  ["PTB", "Please text back"],
  ["TIA", "Thanks in advance"],
  ["BUMP", "Bring up my post"],
  ["OMW", "On my way"],
  ["GRATZ", "Congratulations"],
  ["GL", "Good luck"],
  ["IDK", "I don’t know"],
  ["TTYL", "Talk to you later"],
  ["BRB", "Be right back"],
  ["W8", "Wait"],
  ["NFS", "Not for sale"],
  ["B4N", "Bye for now"],
  ["B@U", "Back at you"],
  ["BBBG", "Bye bye be good"],
  ["BBIAS", "Be back in a sec"],
  ["RUOK", "Are you OK?"],
  ["CYT", "See you tomorrow"],
  ["DBMIB", "Don’t bother me I’m busy"],
  ["DM", "Direct message"],
  ["GFN", "Gone for now"],
  ["143", "I love you"],
  ["2DAY", "Today"],
  ["4EAE", "Forever and ever"],
  ["AF", "As fuck"],
  ["ADN", "Any day now"],
  ["AFAIK", "As far as I know"],
  ["AFK", "Away from keyboard"],
  ["ATM", "At the moment"],
  ["BFN", "Bye for now"],
  ["BOL", "Be on later / Best of luck / Bust out laughing"],
  ["BRB", "Be right back"],
  ["BTW", "By the way"],
  ["CTN", "Can’t talk now"],
  ["DM", "Direct message"],
  ["DWBH", "Don’t worry, be happy"],
  ["F2F", "F2F or Face to face"],
  ["FOMO", "Fear of missing out"],
  ["FWIW", "For what it’s worth"],
  ["GAL", "Get a life"],
  ["GB", "Goodbye"],
  ["GG", "Good game"],
  ["GLHF", "Good luck, have fun"],
  ["GTG", "Got to go; good to go"],
  ["H8", "Hate"],
  ["HAK", "Hugs and kisses"],
  ["HAND", "Have a nice day"],
  ["HMU", "Hit me up"],
  ["HTH", "Hope this helps / Happy to help / How the h---"],
  ["HW", "Homework"],
  ["ICYMI", "In case you missed it"],
  ["IDK", "I don’t know"],
  ["IIRC", "If I remember correctly"],
  ["IKR", "I know, right?"],
  ["ILY", "I love you"],
  ["ILU", "I love you"],
  ["IM", "Instant message"],
  ["IMHO", "In my honest opinion / In my humble opinion"],
  ["IMO", "In my opinion"],
  ["IRL", "In real life"],
  ["IU2U", "It’s up to you"],
  ["IYKWIM", "If you know what I mean"],
  ["JK", "Just kidding"],
  ["J4F", "Just for fun"],
  ["JIC", "Just in case"],
  ["JSYK", "Just so you know"],
  ["KFY", "Kiss for you"],
  ["L8", "Late"],
  ["LMAO", "Laughing my a-- off"],
  ["LMK", "Let me know"],
  ["LOL", "Laugh out loud"],
  ["LSR", "Loser"],
  ["MIRL", "Meet in real life"],
  ["MOS", "Mom over shoulder"],
  ["NAGI", "Not a good idea"],
  ["NM", "Never mind / Not much"],
  ["NMU", "Not much, you?"],
  ["NP", "No problem"],
  ["NTS", "Note to self"],
  ["OIC", "Oh I see"],
  ["OMFG", "Oh my f------ god"],
  ["OMG", "Oh my god"],
  ["ORLY", "Oh, really?"],
  ["OT", "Off-topic"],
  ["OTP", "On the phone / One true pairing"],
  ["P911", "Parent alert"],
  ["PAW", "Parents are watching"],
  ["PCM", "Please call me"],
  ["PIR", "Parent in room"],
  ["PLS", "PLS or Please"],
  ["PLZ", "PLZ or Please"],
  ["PPL", "People"],
  ["POS", "Parents over shoulder / Piece of s---"],
  ["PTB", "Please text back"],
  [
    "QQ",
    "Crying (This abbreviation produces an emoticon in text; it’s often used sarcastically or as part of trash talk during video games.)",
  ],
  ["RAK", "Random act of kindness"],
  ["RL", "Real life"],
  ["RN", "Right now"],
  ["ROFL", "Rolling on the floor laughing"],
  ["RT", "Retweet"],
  ["RUOK", "Are you okay?"],
  ["SMH", "Shaking my head"],
  ["SOS", "Someone over shoulder"],
  ["SRSLY", "Seriously"],
  ["SSDD", "Same stuff, different day"],
  ["STFU", "Shut the f--- up"],
  ["SUS", "Suspicious"],
  ["SWAK", "Sealed with a kiss"],
  ["SWYP", "So, what’s your point?"],
  ["SYS", "See you soon"],
  ["TBC", "To be continued"],
  ["THX", "Thanks"],
  ["TIME", "Tears in my eyes"],
  ["TL;DR", "TL;Too long, didn’t read"],
  ["TMI", "Too much information"],
  ["TMRW", "Tomorrow"],
  ["TTYL", "Talk to you later"],
  ["TY", "TY or Thank you"],
  ["TU", "TY or Thank you"],
  ["VSF", "Very sad face / very severely f------ (in big trouble)"],
  ["WB", "Welcome back"],
  ["WTH", "What the h---"],
  ["WTF", "What the f---"],
  ["WTPA", "Where’s the party at?"],
  ["WYCM", "Will you call me?"],
  ["YGM", "You get me (you understand me)"],
  ["YOLO", "You only live once"],
  ["YW", "You’re welcome"],
  ["ZOMG", "Oh my god (emphatic)"],
  ["ASL", 'Age/sex/location / "As h---"'],
  ["FWB", "Friends with benefits (friends who occasionally have casual sex)"],
  ["FYEO", "FYEO or For your eyes only (may indicate explicit photos)"],
  ["4YEO", "FYEO or For your eyes only (may indicate explicit photos)"],
  ["GYPO", "Get your pants off"],
  ["IWSN", "I want sex now"],
  ["KPC", "Keeping parents clueless"],
  ["LMIRL", "Let’s meet in real life"],
  ["NIFOC", "Naked in front of computer"],
  ["NSFW", "Not safe for work"],
  [
    "OC",
    "Open crib (no parents will be home) / (may also stand for Original Character, a unique character in fan-art or fan fiction not found in the original property)",
  ],
  ["TDTM", "Talk dirty to me"],
];
